// Code generated by counterfeiter. DO NOT EDIT.
package mortemsfakes

import (
	"sync"

	"github.com/google/go-github/v32/github"
	"github.com/ostenbom/morty/mortems"
)

type FakeGitService struct {
	CommitNewBlobsStub        func([]*github.Blob) error
	commitNewBlobsMutex       sync.RWMutex
	commitNewBlobsArgsForCall []struct {
		arg1 []*github.Blob
	}
	commitNewBlobsReturns struct {
		result1 error
	}
	commitNewBlobsReturnsOnCall map[int]struct {
		result1 error
	}
	GetTreeEntriesStub        func() ([]*github.TreeEntry, error)
	getTreeEntriesMutex       sync.RWMutex
	getTreeEntriesArgsForCall []struct {
	}
	getTreeEntriesReturns struct {
		result1 []*github.TreeEntry
		result2 error
	}
	getTreeEntriesReturnsOnCall map[int]struct {
		result1 []*github.TreeEntry
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitService) CommitNewBlobs(arg1 []*github.Blob) error {
	var arg1Copy []*github.Blob
	if arg1 != nil {
		arg1Copy = make([]*github.Blob, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.commitNewBlobsMutex.Lock()
	ret, specificReturn := fake.commitNewBlobsReturnsOnCall[len(fake.commitNewBlobsArgsForCall)]
	fake.commitNewBlobsArgsForCall = append(fake.commitNewBlobsArgsForCall, struct {
		arg1 []*github.Blob
	}{arg1Copy})
	fake.recordInvocation("CommitNewBlobs", []interface{}{arg1Copy})
	fake.commitNewBlobsMutex.Unlock()
	if fake.CommitNewBlobsStub != nil {
		return fake.CommitNewBlobsStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.commitNewBlobsReturns
	return fakeReturns.result1
}

func (fake *FakeGitService) CommitNewBlobsCallCount() int {
	fake.commitNewBlobsMutex.RLock()
	defer fake.commitNewBlobsMutex.RUnlock()
	return len(fake.commitNewBlobsArgsForCall)
}

func (fake *FakeGitService) CommitNewBlobsCalls(stub func([]*github.Blob) error) {
	fake.commitNewBlobsMutex.Lock()
	defer fake.commitNewBlobsMutex.Unlock()
	fake.CommitNewBlobsStub = stub
}

func (fake *FakeGitService) CommitNewBlobsArgsForCall(i int) []*github.Blob {
	fake.commitNewBlobsMutex.RLock()
	defer fake.commitNewBlobsMutex.RUnlock()
	argsForCall := fake.commitNewBlobsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitService) CommitNewBlobsReturns(result1 error) {
	fake.commitNewBlobsMutex.Lock()
	defer fake.commitNewBlobsMutex.Unlock()
	fake.CommitNewBlobsStub = nil
	fake.commitNewBlobsReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitService) CommitNewBlobsReturnsOnCall(i int, result1 error) {
	fake.commitNewBlobsMutex.Lock()
	defer fake.commitNewBlobsMutex.Unlock()
	fake.CommitNewBlobsStub = nil
	if fake.commitNewBlobsReturnsOnCall == nil {
		fake.commitNewBlobsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.commitNewBlobsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeGitService) GetTreeEntries() ([]*github.TreeEntry, error) {
	fake.getTreeEntriesMutex.Lock()
	ret, specificReturn := fake.getTreeEntriesReturnsOnCall[len(fake.getTreeEntriesArgsForCall)]
	fake.getTreeEntriesArgsForCall = append(fake.getTreeEntriesArgsForCall, struct {
	}{})
	fake.recordInvocation("GetTreeEntries", []interface{}{})
	fake.getTreeEntriesMutex.Unlock()
	if fake.GetTreeEntriesStub != nil {
		return fake.GetTreeEntriesStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getTreeEntriesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeGitService) GetTreeEntriesCallCount() int {
	fake.getTreeEntriesMutex.RLock()
	defer fake.getTreeEntriesMutex.RUnlock()
	return len(fake.getTreeEntriesArgsForCall)
}

func (fake *FakeGitService) GetTreeEntriesCalls(stub func() ([]*github.TreeEntry, error)) {
	fake.getTreeEntriesMutex.Lock()
	defer fake.getTreeEntriesMutex.Unlock()
	fake.GetTreeEntriesStub = stub
}

func (fake *FakeGitService) GetTreeEntriesReturns(result1 []*github.TreeEntry, result2 error) {
	fake.getTreeEntriesMutex.Lock()
	defer fake.getTreeEntriesMutex.Unlock()
	fake.GetTreeEntriesStub = nil
	fake.getTreeEntriesReturns = struct {
		result1 []*github.TreeEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeGitService) GetTreeEntriesReturnsOnCall(i int, result1 []*github.TreeEntry, result2 error) {
	fake.getTreeEntriesMutex.Lock()
	defer fake.getTreeEntriesMutex.Unlock()
	fake.GetTreeEntriesStub = nil
	if fake.getTreeEntriesReturnsOnCall == nil {
		fake.getTreeEntriesReturnsOnCall = make(map[int]struct {
			result1 []*github.TreeEntry
			result2 error
		})
	}
	fake.getTreeEntriesReturnsOnCall[i] = struct {
		result1 []*github.TreeEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeGitService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.commitNewBlobsMutex.RLock()
	defer fake.commitNewBlobsMutex.RUnlock()
	fake.getTreeEntriesMutex.RLock()
	defer fake.getTreeEntriesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ mortems.GitService = new(FakeGitService)
